stage_index_homepage:
    path:     /
    defaults: { _controller: STAGEIndexBundle:Pagegarde:index }


projects_index_homepage:
    path:     /Projects/
    defaults: { _controller: STAGEIndexBundle:Projects:projects }


liste_index_homepage:
    path:     /liste/
    defaults: { _controller: STAGEIndexBundle:Projects:liste }

search_index_homepage:
    path:     /search/
    defaults: { _controller: STAGEIndexBundle:Projects:search }



new_index_homepage:
    path:     /new/
    defaults: { _controller: STAGEIndexBundle:Projects:new }

new2_index_homepage:
    path:     /new2/
    defaults: { _controller: STAGEIndexBundle:Projects:new2 }

modify_index_homepage:
    path:     /modify/{id}/
    defaults: { _controller: STAGEIndexBundle:Projects:modify }
    requirements:
        id: \d+


delete_index_homepage:
    path:     /delete/{id}/
    defaults: { _controller: STAGEIndexBundle:Projects:delete }
    requirements:
        id: \d+

view_index_homepage:
    path:     /view/{id}/
    defaults: { _controller: STAGEIndexBundle:Projects:view }
    requirements:
        id: \d+
