<?php

namespace STAGE\IndexBundle\Repository;

/**
 * ProjectEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
